name = "ddg"
description = "Performs a DuckDuckGo search using the duckduckgo_mcp_interface."
command = "python -c \"import asyncio; from slash_commands import run_duckduckgo; asyncio.run(run_duckduckgo())""